import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import { AuthProvider } from "@/components/auth-provider";
import { SiteHeader } from "@/components/site-header";
import { getCurrentUser } from "@/lib/auth-dal";
import "./globals.css";

const font = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Team Chat Application",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const initialUser = await getCurrentUser();

  return (
    <html lang="en" className={`${font.variable} ${font.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AuthProvider initialUser={initialUser}>
          <SiteHeader />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
