import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import { AuthProvider } from "@/components/providers/auth-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { SiteHeader } from "@/components/site-header";
import { getCurrentUser } from "@/lib/auth-dal";
import "./globals.css";

const font = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Team Chat Application",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const initialUser = await getCurrentUser();

  return (
    <html
      lang="en"
      // 抑制 React 的水合警告，
      suppressHydrationWarning
      className={`${font.variable} ${font.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          // 通过修改 class 来切换主题，避免使用 自定义 属性，减少 CSS 选择器的复杂度
          attribute="class"
          defaultTheme="system"
          enableSystem
          // 主题切换时关闭动画
          disableTransitionOnChange
        >
          <AuthProvider initialUser={initialUser}>
            <SiteHeader />
            {children}
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
