import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

// 自托管 Open Sans，经 CSS 变量挂到页面
const font = Open_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Team Chat Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${font.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
